### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by xJREB** [panter/vue-i18next#22]
Would you consider adding TypeScript support to your project? This would make it even more useful. :)

**Comment by claudiocro** [comment]
Typescript support as of version `0.10.0`

https://github.com/panter/vue-i18next/pull/25

**Comment by xJREB** [comment]
Wow, great stuff, thank you! :)

Just one comment: Can you make the `options` argument in the constructor optional like seen below?

```TypeScript
declare class VueI18Next {
  constructor(i18next: i18n, options?: VueI18NextOptions);
...
```

**Comment by claudiocro** [comment]
coming in a few minutes: https://github.com/panter/vue-i18next/pull/26

**Comment by xJREB** [comment]
Sorry, could have provided a pull request... Thank you very much! Works great now! 👍

**Comment by kpturner** [comment]
I am afraid the typescript support is pretty minimal.  There is no exported interface for the VueI18Next class so you cannot declare a variable of type VueI18Next (or interface thereof)
