### ISSUE TITLE
Add filter for $t

### ISSUE THREAD

**Issue by Fohlen** [panter/vue-i18next#23]
Adding a filter like:

```
Vue.filter('t', (value) => {
  if (!value) return ''
  return i18n.t(value)
})
``` 
greatly improves readability and de-clutters the code (given `i18n` is your i18n instance). Maybe should think about adding this as a standard functionality.
A practical example would be:
```
{{ $t('some_text') }}
{{ 'some text' | t }}
```

**Comment by claudiocro** [comment]
Hi

I like your proposal, but I don't want to move further away from the i18next api and your improvement is already possible without any code changes. I will add your filter code to the `docs`.

Thank you!
