### ISSUE TITLE
Translation arguments to i18next component to translate the "path" prop

### ISSUE THREAD

**Issue by itzstatic** [panter/vue-i18next#30]
I'm trying to implement a paging footer 
![image](https://user-images.githubusercontent.com/7293288/42526646-6b6ec328-8444-11e8-9ee6-d6fcc2d86e4c.png)
that needs to be localized to display any text, inline with the select component. Naturally, It is a single key in the culture json:

`"footer": "Candidates {{pagination}} of {{count}}"`

and is used by an i18n component:

```
<i18next tag="span" path="my.key.prefix.footer">
        <... place="pagination" ... />
        <... place="count" ... />
</i18next>
```
Although this properly displays, it does not allow me to use `count` to pluralize, because i18n isn't actually seeing the count.

One solution is for i18next component to receive some sort of translation arguments prop. 

I suppose another could be for the component to take exactly 1 of a `format` or `path`  prop. Allowing me to translate my path in my parent, then passing the result into format would also solve the completely unrelated issue wherein I'm currently having to rewrite my parent component's `i18nOptions `component option's `keyPrefix`. Like:

```
<i18next tag="span" :format="$t('footer', { count: ... })">
        <... place="pagination" ... />
        <... place="count-to-display" ... />
</i18next>
```

Is something like this possible?

**Comment by claudiocro** [comment]
Version `0.12.0` has been released with a new feature that should solve your problem

https://github.com/panter/vue-i18next#component-interpolation

```
<i18next tag="span" path="my.key.prefix.footer" options="{count: ...}">
        <... place="pagination" ... />
        <... place="count" ... />
</i18next>
```
