### ISSUE TITLE
Site Notice About Documentation Version (Wrong Version)

### ISSUE THREAD

**Issue by ykh** [panter/vue-i18next#44]
Hi
At the first tnx for implementing this useful package :+1: 

A little thing I did found in site home page that mentioned:

> This documentation is for vue-i18next **v0.0.12** or later.

I guess it means `0.12.0` instead of `0.0.12` :)

**Comment by claudiocro** [comment]
Thx, will fix that soon!

**Comment by claudiocro** [comment]
fixed with: https://github.com/panter/vue-i18next/commit/d4654c0bedec371cac610eaced476678c1d29fd3
