### ISSUE TITLE
Update for latest version of i18Next

### ISSUE THREAD

**Issue by amritk** [panter/vue-i18next#47]
Currently does not work with the latest version of i18next, there was some breaking typescript changes. You no longer need to import the types separately as they have included them in the main repo.

https://github.com/i18next/i18next/blob/master/CHANGELOG.md

**Comment by Joeffison** [comment]
True. Because of the breaking changes you will get "this.i18next.on is not a function" if you use the latest versions of i18Next (13.0.0 or above) with the current version 0.13.0 (or below).

**Comment by claudiocro** [comment]
thank for reporting! has been fixed with #49
